### ISSUE TITLE
Question about script

### ISSUE THREAD

**Issue by MISTikus** [gitextensions/gitextensions.plugintemplate#19]
Someone, please tell me were the prebuild script is stored?
I really cant find it)))
It executes, but for my point of view it does not exists))
Like a ghost)

**Comment by maraf** [comment]
Do you mean the `prebuild` target in MSBuild, the one that downloads GitExtensions https://github.com/gitextensions/gitextensions.extensibility/blob/9db79b612d16daead7b976bf96039faeaea7b1a8/src/GitExtensions.Extensibility/build/GitExtensions.Extensibility.targets#L30 ?

It comes from the `GitExtensions.Extensibility` nuget package

**Comment by MISTikus** [comment]
Thank you! I broke my brain trying to find it))
